from datetime import date


class EnumValue:
    def __init__(self, name, value=None, comment=None):
        self.name = name
        self.value = value
        self.comment = comment


class Enum:
    """c-style enumeration class"""

    def __init__(self, name, prefix=""):

        # enum values
        self.values = []
        self.name = name

        self.prefix = prefix

    def add_value(self, name, value=None, comment=None):
        """assuees that the user adds the values in the correct order"""

        self.values.append(EnumValue(name, value=value, comment=comment))


class Variable:
    """c-style variable"""

    def __init__(self,
                 name,
                 primitive,
                 qualifiers=None,
                 array=None,
                 comment=None):
        self.name = name
        self.primitive = primitive
        self.comment = comment
        self.array = array
        self.qualifiers = qualifiers

    def declaration(self):
        """Return a declaration string."""
        if isinstance(self.qualifiers, (list, tuple)):
            qual = " ".join(self.qualifiers) + " "
        elif self.qualifiers is not None:
            qual = str(self.qualifiers) + " "
        else:
            qual = ""

        return '{qual}{prim} {name}{array}'.format(
            qual=qual,
            prim=self.primitive,
            name=self.name,
            array='[{a}]'.format(a=self.array) if self.array else '')


class Struct:
    """c-style struct class"""

    def __init__(self, name, ref_name=None, comment=None):
        self.name = name  # definition name of this struct e.g. Struct_t
        self.ref_name = ref_name  # reference name of this struct e.g. the_struct
        self.variables = []
        self.comment = comment

    def add_variable(self, variable):
        """Add another variable to struct"""
        if not isinstance(variable, (Variable, Struct)):
            raise TypeError("variable must be 'Variable' or 'Struct'")

        self.variables.append(variable)

    def declaration(self):
        """Return a declaration string."""
        if self.ref_name is None:
            raise ValueError('no ref_name supplied for Struct "{name}"'.format(
                name=self.name))

        return '{name} {ref};'.format(name=self.name, ref=self.ref_name)


class Function:
    """c-style function"""

    def __init__(self, name, return_type='void'):
        self.name = name
        self.return_type = return_type

        self.variables = []

    def add_argument(self, var):
        """Add an argument to function"""
        if not isinstance(var, Variable):
            raise TypeError("variable must be of type 'Variable'")

        self.variables.append(var)

    def prototype(self):
        """function prototype string"""
        p = '{ret} {nm}({funcs})'.format(
            ret=self.return_type,
            nm=self.name,
            funcs=', '.join([v.declaration() for v in self.variables])
            if self.variables else 'void')

        return p

    def call(self, *arg):
        """call a function"""
        if not len(arg) == len(self.variables):
            print(arg)
            raise ValueError(
                "number of arguments must match number of variables")

        p = '{name}({args});'.format(
            name=self.name, args=', '.join([str(a) for a in arg]))

        return p


class CodeWriter:

    CPP = "__cplusplus"

    VERSION = "1.1"

    def __init__(self, lf="\n", indent='    '):

        self.line_feed = lf
        self.indent = indent

        # initialize values
        self.commenting = False  # switch for bulk commenting
        self.defs = []  # define levels
        self.switch = []  # switch levels
        self.tabs = 0
        self.text = ''  # code

    def tab_in(self):
        """increase tab level"""
        self.tabs += 1

    def tab_out(self):
        """decrease tab level"""
        if self.tabs > 0:
            self.tabs -= 1

    def reset_tabs(self):
        self.tabs = 0

    def start_comment(self):
        """start a bulk comment"""
        self.add_line('/*')
        self.commenting = True

    def end_comment(self):
        """end a bulk comment"""
        self.commenting = False
        self.add_line('*/')

    def add_autogen_comment(self, source=None):
        """add the auto-gen comment (user can point to the source file if required)"""
        self.start_comment()
        self.add_line(
            "This file was autogenerated using the C-Snake v{version} script".
            format(version=self.VERSION))
        self.add_line(
            "This file should not be edited directly, any changes will be overwritten next time the script is run"
        )
        if source:
            self.add_line(
                "Make any changes to the file '{src}'".format(src=str(source)))
        self.add_line(
            "Source code for C-Snake available at https://github.com/SchrodingersGat/C-Snake"
        )
        self.end_comment()

    def add_license_comment(self, license_, authors, intro=None):
        """Add the license comment."""
        self.start_comment()

        if intro:
            for line in intro.splitlines():
                if line == '':
                    self.add_line()
                else:
                    self.add_line(line)

        year = date.today().year
        if authors:
            for author in authors:
                if author.get('email', None):
                    email = ' <{0}>'.format(author['email'])
                else:
                    email = ''
                self.add_line("Copyright © {year} {name}{email}".format(
                    year=year,
                    name=author['name'],
                    email=email))
        self.add_line()

        if not isinstance(license_, str):
            raise TypeError('license_ must be a string.')
        for line in license_.splitlines():
            self.add_line(line)

        self.end_comment()

    def open_brace(self):
        """open-brace and tab"""
        self.add_line('{')
        self.tab_in()

    def close_brace(self, new_line=True):
        """close-brace and tab-out"""
        self.tab_out()
        self.add(self.indent * self.tabs + '}')
        if new_line:
            self.add_line('')

    def define(self, name, value=None, comment=None):
        """add a define"""
        line = "#define " + name
        if value:
            line += ' ' + str(value)

        self.add_line(line, comment=comment, ignore_tabs=True)

    def start_if_def(self, define, invert=False, comment=None):
        """start an #ifdef block (preprocessor)"""
        self.defs.append(define)
        if invert:
            self.add_line(
                "#ifndef " + define, comment=comment, ignore_tabs=True)
        else:
            self.add_line(
                "#ifdef " + define, comment=comment, ignore_tabs=True)

    def end_if_def(self):
        """end an #ifdef block"""

        if self.defs:
            self.add_line("#endif ", comment=self.defs.pop(), ignore_tabs=True)
        else:
            self.add_line("#endif", ignore_tabs=True)

    def cpp_entry(self):
        """add an 'extern' switch for CPP compilers"""
        self.start_if_def(self.CPP, "Play nice with C++ compilers")
        self.add_line('extern "C" {', ignore_tabs=True)
        self.end_if_def()

    def cpp_exit(self):
        self.start_if_def(self.CPP, "Done playing nice with C++ compilers")
        self.add_line('}', ignore_tabs=True)
        self.end_if_def()

    def start_switch(self, switch):
        """start a switch statement"""
        self.switch.append(switch)
        self.add_line('switch ({sw})'.format(sw=switch))
        self.open_brace()

    def end_switch(self):
        """end a switch statement"""
        self.tab_out()
        self.add('}')
        if self.switch:
            self.add(' // ~switch ({sw})'.format(sw=self.switch.pop()))
        self.add_line()

    def add_case(self, case, comment=None):
        """add a case statement"""
        self.add_line('case {case}:'.format(case=case), comment=comment)
        self.tab_in()

    def add_default(self, comment=None):
        """add a default case statement"""
        self.add_line('default:', comment=comment)
        self.tab_in()

    def break_from_case(self):
        """break from a case"""
        self.add_line('break;')
        self.tab_out()

    def return_from_case(self, value=None):
        """return from a case"""
        self.add_line(
            'return{val};'.format(val=' ' + str(value) if value else ''))
        self.tab_out()

    def add(self, text):
        """add raw text"""
        self.text += text

    def add_line(self, text=None, comment=None, ignore_tabs=False):
        """add a line of (formatted) text"""

        # empty line
        if not text and not comment and not self.commenting:
            self.add(self.line_feed)
            return

        if not ignore_tabs and not self.commenting:
            self.add(self.indent * self.tabs)

        if self.commenting:
            self.add("* ")

        # add the text (if appropriate)
        if text:
            self.add(text)
        # add a trailing comment (if appropriate)
        if comment:
            if text:
                self.add(' ')  # add a space after the text
            self.add('//' + comment)

        self.add(self.line_feed)

    def include(self, file, comment=None):
        """add a c-style include"""
        self.add_line(
            "#include {file}".format(file=file),
            comment=comment,
            ignore_tabs=True)

    def add_enum(self, enum):
        """add a constructed enumeration"""
        if not isinstance(enum, Enum):
            raise TypeError('enum must be of type "Enum"')

        self.add_line("typedef enum")
        self.open_brace()

        for i, v in enumerate(enum.values):
            line = enum.prefix + v.name
            if v.value:
                line += " = " + str(v.value)

            if i < (len(enum.values) - 1):
                line += ","

            self.add_line(line, comment=v.comment)

        self.close_brace(new_line=False)
        self.add(' ' + enum.name + ';')
        self.add_line()

    def add_variable(self, var):
        """add a variable definition"""
        if not isinstance(var, Variable):
            raise TypeError("variable must be of type 'Variable'")

        self.add_line(var.declaration() + ";", comment=var.comment)

    def add_struct(self, struct):
        """add a struct"""
        if not isinstance(struct, Struct):
            raise TypeError("struct must be of type 'Struct'")

        self.add_line("typedef struct")
        self.open_brace()

        for var in struct.variables:
            if isinstance(var, Variable):  # variables within the struct
                self.add_variable(var)
            elif isinstance(var, Struct):  # other structs within the struct
                if var.ref_name is None:
                    raise ValueError('no ref_name provided for struct {name}'.
                                     format(name=var.name))
                self.add_line(var.declaration(), comment=var.comment)

        self.close_brace(new_line=False)
        self.add(' ' + struct.name + ';')
        self.add_line()

    def add_function_prototype(self, func, comment=None):
        """add a function prototype"""
        if not isinstance(func, Function):
            raise TypeError("func must be of type 'Function'")

        self.add_line(func.prototype() + ';', comment=comment)

    def add_function_definition(self, func, comment=None):
        """add a function definition"""
        if not isinstance(func, Function):
            raise TypeError("func must be of type 'Function'")

        self.add_line(func.prototype(), comment=comment)

    def call_function(self, func, *arg):
        """enter a function"""
        if not isinstance(func, Function):
            raise TypeError("func must be of type 'Function'")

        self.add_line(func.call(*arg))

    def write_to_file(self, file):
        """write code to file"""
        with open(file, 'w') as the_file:
            the_file.write(self.text)
